In [28]:
#imporrt module
import tensorflow as tf
import numpy as np

In [39]:
#load data
mnist=tf.keras.datasets.mnist
(X_train,y_train),(X_test,y_test)=mnist.load_data()
X_train,X_test=X_train/255.0,X_test/255.0

In [40]:
# build model
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10,activation='softmax')
])

In [41]:
predictions=model(X_train[:1]).numpy()
print(predictions)

[[0.0951839  0.08657791 0.08924706 0.21233964 0.06780025 0.09852918
  0.10089152 0.07206117 0.11352361 0.06384572]]


In [42]:
tf.nn.softmax(predictions).numpy()

array([[0.09943651, 0.09858443, 0.09884792, 0.11179592, 0.09675053,
        0.09976971, 0.10000568, 0.09716365, 0.10127697, 0.09636867]],
      dtype=float32)

In [43]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [44]:
loss_fn(y_train[:1], predictions).numpy()

2.3048906

In [46]:
model.compile(
    optimizer='adam',
    loss=loss_fn,
    metrics=['accuracy']
)

In [47]:
#Train and evaluate model

model.fit(X_train,y_train,epochs=5)

Epoch 1/5


c:\Users\91876\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend.py:5714: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 [==============================] - 5s 2ms/step - loss: 0.2980 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1431 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1047 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0850 - accuracy: 0.9739
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0742 - accuracy: 0.9769


In [48]:
model.evaluate(X_test,y_test,verbose=2)

c:\Users\91876\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend.py:5714: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


313/313 - 1s - loss: 0.0704 - accuracy: 0.9785 - 510ms/epoch - 2ms/step


[0.07038520276546478, 0.9785000085830688]

In [49]:
probability_model=tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [50]:
probability_model(X_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533717, 0.08533715, 0.0853376 , 0.08533915, 0.08533715,
        0.0853373 , 0.08533715, 0.23196295, 0.08533727, 0.0853372 ],
       [0.0853368 , 0.08533698, 0.23196846, 0.08533697, 0.0853368 ,
        0.0853368 , 0.0853368 , 0.0853368 , 0.0853368 , 0.0853368 ],
       [0.08548277, 0.22964524, 0.08571495, 0.08549109, 0.08548661,
        0.08549462, 0.08548608, 0.0861799 , 0.08553582, 0.08548283],
       [0.23191932, 0.0853399 , 0.08534634, 0.08533992, 0.08533992,
        0.08534005, 0.08534064, 0.08534596, 0.08533992, 0.085348  ],
       [0.08557703, 0.08557588, 0.08558218, 0.0855759 , 0.22813654,
        0.08557589, 0.08557612, 0.08560809, 0.08557708, 0.08721533]],
      dtype=float32)>